### ISSUE TITLE
postgres化

### ISSUE THREAD

**Issue by yoshinari21** [born-in-makuhari/emaki#81]
メタデータは基本postgres使用でOK？
問題なければクローズするのでコメントください。

**Comment by craftpaperbag** [comment]
ポスグレ化はsearch #44 でやることにしませんか？

**Comment by craftpaperbag** [comment]
あ、これは質問イシューかな。

**Comment by yoshinari21** [comment]
せや。

**Comment by yoshinari21** [comment]
ポスグレ化はsearch #44 でやることにしませんか？
⇒とくにpostgres化問題ないはずなので、これはクローズで。
#44でやって問題ないです。

**Comment by craftpaperbag** [comment]
#44 はイテ2としているので、
ポスグレ化and検索実装はイテ2でやろう

なお、redisはセッションストアDBで使い続ける。
